name: IoT_Gateway
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    networks:
      - mqtt-net

  coordinator:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.coordinator
    container_name: coordinator
    environment:
      MQTT_SERVER: "mosquitto"
      MQTT_PORT: "1883"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/docker-compose.yml
    depends_on:
      - mqtt
    networks:
      - mqtt-net

  iot_node:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.iot
    #container_name: iot_node
    environment:
      MQTT_SERVER: "mosquitto"
      MQTT_PORT: "1883"
#      SENSOR_ID: "2"
    deploy:
      replicas: 5
    depends_on:
      - mqtt
    networks:
      - mqtt-net

  gateway:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway
    #container_name: gateway
    environment:
      MQTT_SERVER: "mosquitto"
      MQTT_PORT: "1883"
#      GATEWAY_ID: "1"
    deploy:
      replicas: 2
    depends_on:
      - mqtt
    networks:
      - mqtt-net
      - cloud-api-net

  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra-net
    volumes:
      - cassandra1_data:/var/lib/cassandra

# Example of adding another node to this service
#  cassandra2:
#    image: cassandra:4.1
#    container_name: cassandra2
#    hostname: cassandra2
#    environment:
#      - CASSANDRA_CLUSTER_NAME=TestCluster
#      - CASSANDRA_SEEDS=cassandra1
#      - CASSANDRA_LISTEN_ADDRESS=cassandra2
#      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    depends_on:
#      - cassandra1
#    volumes:
#      - cassandra2_data:/var/lib/cassandra
#    networks:
#      - cassandra-net

  database-api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.database-api
    container_name: database-api
    hostname: database-api
    environment:
      CASSANDRA_IP: "cassandra1"
      CASSANDRA_PORT: "9042"
      SERVER_HOST: "0.0.0.0"
      PORT: "8000"
      REPLICATION_FACTOR: "1" # RF
      CONSISTENCY_LEVEL: "one" # one or quorum, quorum asks ceil(RF/2)+1 nodes before write or read is succesful.
    ports:
      - "8000:8000"
    networks:
      - cassandra-net
      - cloud-api-net
    depends_on:
      - cassandra1
    restart: unless-stopped # It takes a while for cassandra to setup, so this can't connect right away and exits


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - cassandra-net
      - mqtt-net
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/certs:/certs:rw
    environment:
      GF_INSTALL_PLUGINS: "hadesarchitect-cassandra-datasource,grafana-mqtt-datasource"

networks:
  mqtt-net:
  cloud-api-net:
  cassandra-net:

volumes:
  cassandra1_data:
