FROM python:3.10

WORKDIR /app

COPY ../src/cloud/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../src/cloud/api/ .


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]